Repository openshift/aws-account-operator, pull requests merged in 2019-08, with the labels that each got.

#97 Initialize all regions with a EC2 instance
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm, size/L

#106 Fix error message formatting
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/XS

#108 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#96 SREP-1593 Account Reuse
  deploy/crds/aws_v1alpha1_account_crd.yaml
  deploy/crds/aws_v1alpha1_accountclaim_5_cr.yaml
  deploy/crds/aws_v1alpha1_accountclaim_6_cr.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/iam.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountclaim/reuse.go
  pkg/controller/accountpool/accountpool_controller.go
  pkg/localmetrics/localmetrics.go
Labels: approved, size/XL

#107 SREP-1792: Error if sts token output is nil
  pkg/controller/account/account_controller.go
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/S

#111 SREP-1871 Get AWS credentials from account instead of accountClaim obj
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/S

#112 SREP-1879 Skip finalizer function if accountLink is empty in accountClaim
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: approved, lgtm, size/M

#113 Created endpoint/register for reuse metrics
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#114 Reduce STS credential duration until we update roles
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/XS

#115 SREP-1883 aws-account-operator increase support case check interval
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#116 increase account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#104 Fix for pending verification bug: SREP-1797
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm, size/M

#121 Check length on instance slice before assigning
  pkg/controller/account/ec2.go
Labels: approved, lgtm, size/S

#119 Modified Reuse metric to include ID
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/S

#123 SREP-1958
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
Labels: approved, lgtm, size/XS

#122 Revert "Modified Reuse metric to include ID"
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/S

#126 Added Nina Taneja as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#127 Bump account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#117 SREP-1918
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#120 SREP-1792: Add extra protections to aws client
  pkg/awsclient/client.go
Labels: approved, lgtm, size/XS

#130 Regenerate CRDs to match current definitions
  deploy/crds/aws_v1alpha1_account_crd.yaml
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  deploy/crds/aws_v1alpha1_accountpool_crd.yaml
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#131 Add return statement
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#132 Fix account CRD indentation
  deploy/crds/aws_v1alpha1_account_crd.yaml
Labels: approved, lgtm, size/XS

#134 SREP-1950 - Fix for CI clusters burning accounts
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: approved, lgtm, size/XS

#129 Small capitalization fix
  deploy/crds/aws_v1alpha1_account_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
Labels: approved, lgtm, size/XS

#125 New fix for adding LegalID to Reuse Metric
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/S

#135 SREP-1987 Fix Ready accounts metric
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/XS

#136 SREP-1989 Bump limit to 4450
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#109 Add updated documentation
  README.md
Labels: approved, lgtm, size/L
