Repository openshift/aws-account-operator, pull requests merged in 2019-10, with the labels that each got.

#174 Add language to created AWS Case
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#175 Update to operator-custom-metrics v0.2.1
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/builder.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metrics.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metricsconfig.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/service.go
Labels: approved, lgtm, size/L

#177 Correct service name to match whats on cluster and in monitoring
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#178 Implement AWSFederateRole controller
  deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/add_awsfederatedrole.go
  pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/XL

#179 AWSFederatedRole CR Typo fix
  deploy/crds/aws_v1alpha1_awsfederatedrole_customeradmin_cr.yaml
Labels: approved, lgtm, size/XS

#172 MVP for AWSFederatedAccountAccess controller
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_customeradmin_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/add_awsfederatedaccountaccess.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#181 Change secret reference to account name reference
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#184 Updated OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#182 Add BYOC field to account spec
  deploy/crds/aws_v1alpha1_account_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS

#185 Add BYOC fields to AccountClaim Spec
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#187 Add claimLinkNamespace field to Account CR
  deploy/crds/aws_v1alpha1_account_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/S

#171 Move check for awslimit outside of reconcile.
  cmd/manager/main.go
  pkg/controller/account/account_controller.go
  pkg/controller/utils/conditions.go
  pkg/localmetrics/localmetrics.go
  pkg/totalaccountwatcher/totalaccountwatcher.go
  pkg/totalaccountwatcher/totalaccountwatcher_test.go
Labels: approved, lgtm, size/L

#186 Implement BYOC AccountClaim logic
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountclaim/reuse.go
  pkg/controller/accountpool/accountpool_controller.go
  pkg/controller/accountpool/accountpool_controller_test.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L
