Repository openshift/aws-account-operator, pull requests merged in 2019-09, with the labels that each got.

#140 SREP-2029 Increase account limit to 4550
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#143 Bump AWS account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#144 Don't create account if AwsAccountID exists
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/M

#142 Added logic to delete bucket objects
  pkg/awsclient/client.go
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/M

#145 Bump AWS account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#146 Bump AWS account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#147 Added better error handling reuse.go
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/M

#148 Spelling and readability changes to README
  README.md
Labels: approved, lgtm, size/S

#153 Bump AWS account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#152 Add permissive option to image registry initializer
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/XS

#150 Fix formatting and spelling
  pkg/controller/account/credentials_rotator.go
Labels: approved, lgtm, size/XS

#133 validate yaml in pr_check
  hack/app_sre_pr_check.sh
  hack/validate_yaml.py
Labels: approved, lgtm, size/M

#137 Created Go Routine to update total AWS Accounts every N hours
  cmd/manager/main.go
  pkg/controller/account/account_controller.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/M

#149 Explicitly support * on accountpools
  deploy/cluster_role.yaml
Labels: approved, lgtm, size/XS

#157 Wait for all routines to finish, don't log errors twice
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/S

#138 SREP-1979 Implement unit tests for accountpool controller
  Gopkg.lock
  pkg/controller/accountpool/accountpool_controller_test.go
Labels: approved, lgtm, size/L

#159 Explicitly call out namespace in clusterrolebinding
  deploy/cluster_role_binding.yaml
Labels: approved, lgtm, size/XS

#155 SREP-1964 Check status error when updating account status
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#160 Added support for yaml files with multiple documents
  hack/validate_yaml.py
Labels: approved, lgtm, size/XS

#161 account bump for integration to work
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#162 Fix removal of subresouces in CRD
  deploy/crds/aws_v1alpha1_account_crd.yaml
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  deploy/crds/aws_v1alpha1_accountpool_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/accountpool_types.go
Labels: approved, lgtm, size/XS

#163 Account limit bump
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#158 Handle and log errors in localmetrics
  pkg/controller/account/account_controller.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/M

#164 add permissions to uhc-cluster-role
  deploy/uhc_cluster_role.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#141 Refactor unclaimed account metric
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/M

#165 increase account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#166 Bump account limit to 4700
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#167 added update configmaps permission to UHC cluster role
  deploy/uhc_cluster_role.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#169 Reverted yaml load function to safe_load
  hack/validate_yaml.py
Labels: approved, lgtm, size/XS

#139 AWS federated access
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_customeradmin_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XXL
