Repository openshift/aws-account-operator, pull requests merged in 2019-07, with the labels that each got.

#87 SREP-1751 - Expose metric with total of accounts in PendingVerification
  pkg/metrics/metrics.go
Labels: approved, lgtm, size/XS

#90 SREP-1762 - Added msg to support case body
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#89 Move to using operator-custom-metrics library for custom metrics
  Gopkg.lock
  cmd/manager/main.go
  pkg/controller/account/account_controller.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountpool/accountpool_controller.go
  pkg/localmetrics/localmetrics.go
  vendor/github.com/openshift/operator-custom-metrics/LICENSE
  vendor/github.com/openshift/operator-custom-metrics/example/example.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/builder.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metrics.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metricsconfig.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/service.go
Labels: approved, lgtm, size/XL

#92 Fix the port number so the route points to the right port
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#93 Added metric for number of ready account CRs
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/S

#94 Fix for pending verification bug: SREP-1698
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/M

#95 Register Ready metric
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#98 Increase account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#99 Revert "Fix for pending verification bug: SREP-1698"
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/M

#100 SREP-1816 Increase limits multiple EC2 instance types
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#103 SREP-1833 Increase account limit to 4000
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS
