Repository openshift/aws-account-operator, pull requests merged in 2019-06, with the labels that each got.

#74 Fix info msg typo
  pkg/controller/accountpool/accountpool_controller.go
Labels: approved, lgtm, size/XS

#75 Bump operator hard AWS account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#73 Refactored service generation to check error
  cmd/manager/main.go
  pkg/metrics/service.go
Labels: approved, lgtm, size/L

#76 Fix typo in function name
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#77 Bump AWS account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#78 Bump account limit
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#70 Update CSV to add prom yamls to bundle output
  deploy/prometheus/prometheus-k8s-role.yaml
  deploy/prometheus/prometheus-k8s-rolebinding.yaml
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/XS

#80 SREP-1602: Update AccountClaim legalEntity.id to string
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  pkg/apis/aws/v1alpha1/accountclaim_types.go
Labels: approved, lgtm, size/XS

#81 Drop AWS Account limit down to 4500
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#79 SREP-1540 Auto Update Account Instance Limits
  deploy/crds/aws_v1alpha1_account_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.defaults.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/L

#84 Log AWS error message
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#86 APPSRE-745 - Lower severity for support cases to urgent
  pkg/controller/account/account_controller.go
Labels: lgtm, size/XS
