Repository openshift/aws-account-operator, pull requests merged in 2019-03, with the labels that each got.

#3 added awsclient library and example of how to implement on the accoun…
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: size/L

#4 Add STS AssumeRole capability
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: size/M

#6 fix issues with current code not compiling
  cmd/manager/main.go
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: size/S

#7 Add account type details and bugfix
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/controller/account/account_controller.go
Labels: size/XS

#5 Implement AccountPool controller
  pkg/apis/aws/v1alpha1/accountpool_types.go
  pkg/controller/accountpool/accountpool_controller.go
Labels: size/M

#8 Added main logic function to account_controller.go
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: size/L

#9 Add spec and remove boilerplate code from controller
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: size/L

#10 Fixed errors in accountpool_controller.go that caused compilation errors
  pkg/controller/accountpool/accountpool_controller.go
Labels: lgtm, size/XS

#12 Fix accountpool CR
  deploy/crds/aws_v1alpha1_accountpool_cr.yaml
Labels: size/XS

#13 Change type of poolsize from string to int
  pkg/apis/aws/v1alpha1/accountpool_types.go
  pkg/controller/accountpool/accountpool_controller.go
Labels: size/XS

#14 Account pool controller bug fixes
  pkg/controller/account/account_controller.go
  pkg/controller/accountpool/accountpool_controller.go
Labels: size/S

#15 Add account status to AccountPool
  pkg/apis/aws/v1alpha1/accountpool_types.go
Labels: size/XS

#16 Fix logic for AccountPool controller to update the status of the CR
  pkg/controller/accountpool/accountpool_controller.go
Labels: lgtm, size/S

#18 Refactor pool status check into a function
  pkg/controller/accountpool/accountpool_controller.go
Labels: size/S

#19 Update account naming scheme
  pkg/controller/accountpool/accountpool_controller.go
Labels: size/XS

#17 Make API usable with the Go client generator
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/accountpool_types.go
  pkg/apis/aws/v1alpha1/register.go
Labels: size/S

#20 This should be the AWS account ID numeric value
  pkg/controller/accountpool/accountpool_controller.go
Labels: size/XS

#22 Paginate through accounts, return err if none found
  pkg/controller/account/account_controller.go
Labels: size/M

#24 Update account claim types
  pkg/apis/aws/v1alpha1/accountclaim_types.go
Labels: size/S

#25 Finished MVP logic for reconcile function
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: size/L

#26 Added pulling aws creds from secret and removed debugging lines
  pkg/controller/account/account_controller.go
Labels: size/S

#28 Added printing details to account crd
  deploy/crds/aws_v1alpha1_account_crd.yaml
Labels: size/XS

#29 Add data to the crds so oc get can see more
  deploy/crds/aws_v1alpha1_accountpool_crd.yaml
Labels: size/S

#27 Add finalizer to the AWS Account objects
  pkg/controller/accountpool/accountpool_controller.go
Labels: size/XS

#30 Update secret namespace to be from request
  pkg/controller/account/account_controller.go
Labels: size/XS
