Repository openshift/aws-account-operator, pull requests merged in 2019-05, with the labels that each got.

#61 Remove billingAccountID from AccountClaim status
  deploy/crds/aws_v1alpha1_account_crd.yaml
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#63 Update AWS account email address
  pkg/controller/accountpool/accountpool_controller.go
Labels: approved, lgtm, size/XS

#64 Deploy needed objects for prometheus metrics when the operator comes up
  cmd/manager/main.go
  deploy/prometheus-k8s-role.yaml
  deploy/prometheus-k8s-rolebinding.yaml
  pkg/metrics/service.go
Labels: approved, lgtm, size/L

#67 Updating owners file
  OWNERS
Labels: approved, lgtm, size/XS

#66 Added account limit checking and better aws error handling
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/L

#69 Moved TotalAwsAccounts to only call if trying to create / prep a new account
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#71 migrate saas repo to gitlab
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/XS

#72 Added aws metrics to account controller
  pkg/controller/account/account_controller.go
  pkg/metrics/metrics.go
Labels: approved, lgtm, size/S
