Repository openshift/aws-account-operator, pull requests merged in 2019-12, with the labels that each got.

#217 add aws-account-operator-client Group to ClusterRoleBinding
  deploy/uhc_cluster_role_binding.yaml
Labels: approved, lgtm, size/XS

#219 Propagate BYOC account errors to accountclaim
  pkg/controller/account/account_controller.go
  pkg/controller/account/byoc.go
Labels: approved, lgtm, size/M

#220 Remove conditions check for invalid lasttransitiontime
  pkg/controller/account/account_controller.go
  pkg/controller/utils/conditions.go
Labels: approved, lgtm, size/S

#226 Add clusterrolebinding to oc template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/M

#228 Revert "Add clusterrolebinding to oc template"
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/M

#229 Ensure we update the status on the accountclaim
  pkg/controller/account/account_controller.go
  pkg/controller/account/credentials_rotator.go
  pkg/controller/account/iam.go
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: approved, lgtm, size/L

#222 Comments AwsLimit variable to conform with Go linting best practices
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#235 Remove finalizer if BYOC
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: approved, lgtm, size/M

#236 Initialize account when creating, use spec AWS account ID
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#237 Remove finalizer from the Account CR if BYOC
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/controller/account/account_controller.go
  pkg/controller/accountpool/accountpool_controller.go
Labels: approved, lgtm, size/M

#221 Changed awsfederatedaccountaccess to use secret reference
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/M

#239 Bump account limit to 4800
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS
