Repository openshift/aws-account-operator, pull requests merged in 2019-04, with the labels that each got.

#31 Implement conditions status for the Account CRDs
  deploy/crds/aws_v1alpha1_account_crd.yaml
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  deploy/crds/aws_v1alpha1_accountpool_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.defaults.go
Labels: size/L

#32 Refactored code and fixed error returning bugs
  pkg/controller/account/account_controller.go
Labels: size/L

#34 Enable cluster-scoping for operator
  cmd/manager/main.go
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: size/S

#36 Fix genclient tag
  pkg/apis/aws/v1alpha1/accountclaim_types.go
Labels: size/XS

#33 Added EC2 building and termination
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: size/L

#35 Create prometheus metrics
  pkg/metrics/metrics.go
Labels: size/L

#37 Copy secret referenced by Account to secret that UHC expects
  deploy/crds/aws_v1alpha1_account_crd.yaml
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  deploy/crds/aws_v1alpha1_accountpool_cr.yaml
  deploy/crds/aws_v1alpha1_accountpool_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/accountpool_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: size/L

#38 Add deploy scripts
  config/templates/aws-account-operator-csv-template.yaml
  deploy/operator.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/app_sre_pr_check.sh
  hack/generate-operator-bundle.py
  hack/olm-registry/olm-artifacts-template.yaml
Labels: size/L

#39 Add Dockerfile and Makefile
  Makefile
  build/Dockerfile
Labels: size/M

#41 Fix Makefile
  Makefile
Labels: size/XS

#42 AccountClaim crd name is plural
  config/templates/aws-account-operator-csv-template.yaml
Labels: size/XS

#43 Duplicate word
  config/templates/aws-account-operator-csv-template.yaml
Labels: size/XS

#40 Expose metrics when Operator start. Update metrics in respecitve reconcile loops
  cmd/manager/main.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountpool/accountpool_controller.go
  pkg/metrics/metrics.go
Labels: size/M

#44 Added account total to metrics
  pkg/metrics/metrics.go
Labels: size/S

#45 Rename role_binding and role to cluster_role_binding and cluster_role
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  hack/generate-operator-bundle.py
Labels: size/XS

#47 Implemented conditions for account controller
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/controller/account/account_controller.go
  pkg/controller/utils/conditions.go
Labels: size/M

#46 Add service account aws-account-operator-client for UHC
  deploy/uhc_cluster_role.yaml
  deploy/uhc_cluster_role_binding.yaml
  deploy/uhc_service_account.yaml
  hack/generate-operator-bundle.py
Labels: size/M

#48 Don't use Yaml list
  deploy/uhc_cluster_role.yaml
  deploy/uhc_cluster_role_binding.yaml
  deploy/uhc_service_account.yaml
Labels: size/M

#49 Updated AWS secret name
  pkg/controller/account/account_controller.go
Labels: size/XS

#51 SREP-1143: Prep for CI pipeline
  Makefile
  OWNERS
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  config/config.go
  project.mk
  standard.mk
Labels: lgtm, size/L

#50 Update conditions before updating status
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#52 Use ENV for docker image name if it exists
  standard.mk
Labels: approved, lgtm, size/XS

#55 Added failures anywhere we could return an error
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#56 Added creation failure if hung for 10 minutes
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#53 Set pool and claim controllers to use specific namespace for accounts
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/controller/account/account_controller.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountpool/accountpool_controller.go
Labels: approved, lgtm, size/M

#54 Bug Fix: accountpool status now correctly shows counts when doing oc get
  deploy/crds/aws_v1alpha1_accountpool_crd.yaml
Labels: approved, lgtm, size/XS

#57 Make sure we provide the AWS secret access key
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: approved, lgtm, size/S

#58 Fix account status jsonpath
  deploy/crds/aws_v1alpha1_account_crd.yaml
Labels: approved, lgtm, size/XS

#59 Added admin policy attachment to IAM user
  pkg/awsclient/client.go
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/M

#60 One update an object once inside the reconcile loop
  pkg/controller/account/account_controller.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountpool/accountpool_controller.go
Labels: approved, lgtm, size/L
