Repository openshift/aws-account-operator, pull requests merged in 2019-11, with the labels that each got.

#189 Add check for AWSCustomPolicy and AWSManagedPolicies
  pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
Labels: approved, lgtm, size/M

#190 CreateOrUpdate logic for Self-service IAM Roles and Policies
  pkg/awsclient/client.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/M

#191 Added dofinn as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#192 InitializeSupportedRegions takes an AWS Client instead of a set of credentials
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm, size/S

#173 Expand aws api errors
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm, size/L

#193 Copy LegalID from claim to account for BYOC
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: approved, lgtm, size/XS

#196 Support arbitrary role in getStsCredentials and BuildSTSUser
  pkg/controller/account/account_controller.go
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/M

#194 Refactor aws errors
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
  pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#197 CreateIAMUser fix
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#198 Remove early success message in IAM account creation
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#200 Revert "InitializeSupportedRegions takes an AWS Client instead of a set of credentials"
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm, size/S

#201 Add missing role name to credentials rotator
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/credentials_rotator.go
Labels: approved, lgtm, size/S

#202 Update FAA CR
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
Labels: approved, lgtm, size/XS

#183 Refresh web console signin token
  deploy/crds/aws_v1alpha1_account_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/credentials_rotator.go
  pkg/controller/account/ec2.go
  pkg/controller/account/iam.go
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/XL

#204 Ignore if the STS secret doesn't exist
  pkg/controller/account/credentials_rotator.go
Labels: approved, lgtm, size/M

#203 Add additional printer column annotations
  deploy/crds/aws_v1alpha1_account_crd.yaml
  deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
  deploy/crds/aws_v1alpha1_accountpool_crd.yaml
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/accountpool_types.go
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
Labels: approved, lgtm, size/M

#195 Initialization of region verification checks unique instance
  pkg/controller/account/ec2.go
Labels: approved, lgtm, size/XS

#205 Change AWS Id to AWS arn
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/S

#206 Ensure we have a timestamp as lastTransitionTime
  pkg/controller/utils/conditions.go
Labels: approved, lgtm, size/XS

#207 Explicitly check conditions LastTransitionTime
  pkg/controller/account/account_controller.go
  pkg/controller/utils/conditions.go
Labels: approved, lgtm, size/S

#208 Revert "Ensure we have a timestamp as lastTransitionTime"
  pkg/controller/utils/conditions.go
Labels: approved, lgtm, size/XS

#188 Implement BYOC Account controller logic
  pkg/controller/account/account_controller.go
  pkg/controller/account/byoc.go
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/L

#209 Set ClaimLinkNamespace when Creating an Account CR
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/XS

#210 Make legalEntity optional again
  deploy/crds/aws_v1alpha1_account_crd.yaml
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS

#211 Automatically generate CRDs in CSV
  config/templates/aws-account-operator-csv-template.yaml
  deploy/cluster_role.yaml
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/M

#213 CSV require a description for CRDs
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/XS

#214 Add CRD name
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/XS

#216 Refactor BYOC init to smaller functions
  pkg/controller/account/account_controller.go
  pkg/controller/account/byoc.go
Labels: approved, lgtm, size/L

#218 Handle error for BYOC aws client setup
  pkg/controller/account/byoc.go
Labels: approved, lgtm, size/XS
