Repository openshift/aws-account-operator, pull requests merged in 2020-09, with the labels that each got.

#459 Detect and recover stale region initialization
  cmd/manager/main.go
  pkg/controller/account/account_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm

#429 OSD-3978 Refactor error handling & logging, reconcile logic for CCS account initialization for flexible re-queuing (pt 2)
  pkg/controller/account/account_controller.go
  pkg/controller/account/account_finalizer.go
  pkg/controller/account/byoc.go
Labels: approved, lgtm

#393 Cleans up Legacy Permissions into blocks.
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Labels: approved, lgtm

#438 Adds Permission needed to add transitgateway self-service
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
  test/integration/federated_access_cr_test.go
Labels: approved, lgtm

#462 OSD-5077 Lock registry image in 4.5
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#463 Tiny Fix: Rename function parameter for linter
  pkg/controller/account/ec2.go
Labels: approved, lgtm

#441 Reconciler metrics: count errors
  pkg/controller/account/account_controller.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountpool/accountpool_controller.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
  pkg/controller/utils/reconcilermetrics.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm

#439 Refactors Account Struct to have methods
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/account_controller_test.go
  pkg/controller/account/byoc.go
  pkg/controller/utils/conditions.go
Labels: approved, lgtm, tide/merge-method-squash

#461 Refactor ou logic
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/controller/accountclaim/organizational_units.go
  pkg/controller/accountclaim/organizational_units_test.go
Labels: approved, lgtm

#465 Consolidates Readme and creates Docs dir
  README.md
  docs/1.0-Installation.md
  docs/2.0-Custom-Resources.md
  docs/3.0-Controllers.md
  docs/4.0-Special-Items-Main-Go.md
Labels: approved, lgtm

#471 Clarifies environment variable setup instructions and fixes some linter issues for README.md
  README.md
Labels: approved, lgtm, size/XS

#475 Delay requeue when account limit reached
  pkg/controller/account/account_controller.go
Labels: approved, lgtm

#473 Time InitializingRegions by Condition
  pkg/controller/account/account_controller.go
Labels: approved, lgtm

#443 Consolidate duplicate pkg/controller/utils imports
  pkg/controller/account/ec2.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm

#469 Add role for ccs access
  cmd/manager/main.go
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
  pkg/controller/account/byoc.go
  pkg/controller/account/byoc_test.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm

#474 Remove osd-operators-registry targets
  standard.mk
Labels: approved, lgtm

#472 Adds various fixes for Go linter standards
  .golangci.yml
  Makefile
  cmd/manager/main.go
  config/config.go
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
  pkg/awsclient/iam.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/byoc.go
  pkg/controller/account/byoc_test.go
  pkg/controller/account/ec2.go
  pkg/controller/account/iam.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountclaim/accountclaim_controller_test.go
  pkg/controller/accountclaim/reuse.go
  pkg/controller/accountpool/accountpool_controller.go
  pkg/controller/accountpool/accountpool_controller_test.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
  pkg/controller/awsfederatedrole/finalizer.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/utils.go
  pkg/localmetrics/localmetrics.go
  pkg/totalaccountwatcher/totalaccountwatcher.go
  pkg/totalaccountwatcher/totalaccountwatcher_test.go
Labels: approved, lgtm, size/L

#405 Refactor massive account controller Reconcile
  pkg/controller/account/account_controller.go
Labels: approved, lgtm

#467 Deploy configmap in make
  Makefile
  hack/templates/aws_v1alpha1_configmap.tmpl
Labels: approved, lgtm

#477 Adds conditional retry for some specific errors, eg: InvalidClientTokenID
  Gopkg.lock
  pkg/controller/account/account_controller.go
  pkg/controller/account/iam.go
  vendor/github.com/avast/retry-go/LICENSE
  vendor/github.com/avast/retry-go/options.go
  vendor/github.com/avast/retry-go/retry.go
Labels: approved, lgtm

#476 Try and assume BYOCAdminAcccess-uid role during AFAA cleanup
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm

#481 Fixes linting errors
  pkg/awsclient/iam.go
  pkg/controller/accountclaim/organizational_units.go
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm

#482 Fix more linting errors
  Makefile
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm
