Repository openshift/aws-account-operator, pull requests merged in 2020-04, with the labels that each got.

#324 Update gopkg lock to remove unneeded packages
  Gopkg.lock
Labels: approved, lgtm

#323 Fixes new condition occurances timestamps failing to update
  pkg/controller/utils/conditions.go
Labels: approved, lgtm

#325 Add reuse test make target
  Makefile
  hack/templates/aws_v1alpha1_accountclaim_cr.tmpl
Labels: approved, lgtm

#321 Adds random requeue time to credential refresh.
  pkg/credentialwatcher/credentialwatcher_suite_test.go
  pkg/credentialwatcher/credentialwatcher_test.go
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm

#320 Adds deploy target for automating install of the aws-account-operator
  Makefile
  README.md
  hack/files/aws_v1alpha1_zero_size_accountpool.yaml
  hack/templates/aws_v1alpha1_aws_account_operator_credentials.tmpl
Labels: approved, lgtm

#326 Fixes formatting and syntax issues in the README.md
  README.md
Labels: approved, lgtm

#327 Replaces hard-coded data with variables; simplifies some piped commands in Makefile
  Makefile
Labels: approved, lgtm

#329 Set IAM_USER var to create access keys
  hack/scripts/aws/rotate_iam_access_keys.sh
Labels: approved, lgtm

#330 Test scripts
  Makefile
  hack/scripts/test_envs
  test/integration/api/create_account.sh
  test/integration/api/delete_account.sh
  test/integration/api/delete_account_secrets.sh
Labels: approved, lgtm

#328 Add test-all make target
  Makefile
Labels: approved, lgtm

#331 Removes duplicate "name" field from awsCredentialSecret; trailing whitespaces
  hack/templates/aws_v1alpha1_ccs_accountclaim_cr.tmpl
Labels: approved, lgtm

#295 Moves complex logic and simple checks to function that return boolean results
  Makefile
  pkg/controller/account/account_controller.go
  pkg/controller/account/account_controller_test.go
  pkg/controller/account/byoc.go
  pkg/controller/account/byoc_test.go
Labels: approved, lgtm, size/XXL

#332 Fix secret output
  hack/scripts/aws/rotate_iam_access_keys.sh
Labels: approved, lgtm

#333 Fix kubernetes secret output
  hack/scripts/aws/rotate_iam_access_keys.sh
Labels: approved, lgtm

#334 Add documentation for functions in iam.go
  pkg/controller/account/iam.go
Labels: approved, lgtm

#337 Added CreateCustomerGateway perm
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Labels: approved, lgtm

#336 Fix example CRs for Account and FederatedAccountAccess
  deploy/crds/aws_v1alpha1_account_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
Labels: approved, lgtm

#342 Don't return newline char
  hack/scripts/aws/rotate_iam_access_keys.sh
Labels: approved, lgtm

#335 Add label for the target awsAccountID where the role is created
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm

#341 Add tag builder to client
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/awsclient/tags.go
Labels: approved, lgtm

#345 Update tag builder to take account claim, initialize every time
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/awsclient/tags.go
Labels: approved, lgtm

#286 Create function for SecretsCreator
  pkg/controller/account/account_controller.go
  pkg/controller/account/credentials_rotator.go
  pkg/controller/account/iam.go
  pkg/controller/account/secrets.go
  pkg/controller/account/secrets_test.go
Labels: approved, lgtm, size/L

#346 Use root account creds to assume a role in target account for federated role cleanup
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm

#350 Fix Double Logging for Secrets Refresh
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm

#347 Update rotate credentials bool only if false
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm

#352 Add DisableVgwRoutePropagation to networkmgmt role
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Labels: approved, lgtm

#353 Add EnableVgwRoutePropagation to networkmgmt role
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Labels: approved, lgtm

#348 Removes erroneous redirection to stderr in rotate_iam_access_keys.sh
  hack/scripts/aws/rotate_iam_access_keys.sh
Labels: approved, lgtm

#351 Refactor BuildIAMUser
  pkg/controller/account/account_controller.go
  pkg/controller/account/byoc.go
  pkg/controller/account/iam.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm
