Repository openshift/aws-account-operator, pull requests merged in 2020-03, with the labels that each got.

#297 Dockerfile fix
  build/Dockerfile
Labels: approved, lgtm, size/S

#290 Remove unused state constant
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
Labels: approved, lgtm, size/XS

#298 Create make targets for testing Federated Access
  Makefile
  hack/templates/aws_v1alpha1_account.tmpl
  hack/templates/aws_v1alpha1_awsfederatedaccountaccess_cr.tmpl
Labels: approved, lgtm, size/L

#289 Ensure finalizer is added and handled for AWS Federated Roles
  pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
  pkg/controller/awsfederatedrole/finalizer.go
Labels: approved, lgtm, size/L

#300 Fix bug where using same role in account with second user fails
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/L

#303 Adds handling of unexpected AWS API errors
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/S

#305 Fix small typo in error message
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/XS

#304 Handles non-AWS errors returned by createIAMRole function
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/S

#306 Fix namespace on SA
  deploy/uhc_service_account.yaml
Labels: approved, lgtm, size/XS

#307 Only rotate STS credentials when Account CR state is Ready
  cmd/manager/main.go
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/XS

#308 Removes support ticket related code from account_controller.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/cases.go
Labels: approved, lgtm, size/M

#309 Remove owner reference for BYOC accounts from creating accountclaim
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/S

#278 Implement Route53 hosted zone cleanup for reuse
  pkg/awsclient/client.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/L

#312 Adds clcollins to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#313 Added APAC to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#311 add alima to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#315 Removes support:* from FederatedAccessRole
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Labels: approved, lgtm

#317 Handle the new UID assignment to FAA Roles in the Makefile tests
  Makefile
Labels: approved, lgtm

#319 Update OWNERS
  OWNERS
Labels: approved, lgtm

#256 Secret watcher run on startup
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/XS

#294 Aws customer admin role
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: approved, lgtm, size/L

#245 Fix for AccountClaim not registering Account CR being in an error state
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/controller/accountclaim/accountclaim_controller.go
Labels: approved, lgtm, size/M

#284 Local dev mode
  README.md
  cmd/manager/main.go
  pkg/controller/account/account_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#299 Move constants and types that could shared in the package v1alpha1
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/cases.go
  pkg/controller/account/ec2.go
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/L

#302 Finalizer refactor
  pkg/controller/account/account_controller.go
  pkg/controller/account/account_finalizer.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountclaim/accountclaim_finalizer.go
  pkg/controller/utils/utils_test.go
Labels: approved, lgtm, size/L

#322 Ccs make target
  Makefile
  deploy/crds/aws_v1alpha1_accountclaim_1_cr.yaml
  deploy/crds/aws_v1alpha1_accountpool_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
  hack/scripts/aws/rotate_iam_access_keys.sh
  hack/templates/aws_v1alpha1_awsfederatedaccountaccess_cr.tmpl
  hack/templates/aws_v1alpha1_ccs_accountclaim_cr.tmpl
  hack/templates/namespace.tmpl
Labels: approved, lgtm
