Repository openshift/aws-account-operator, pull requests merged in 2020-02, with the labels that each got.

#263 Add finalizer and handling for AWS Federated Account Access
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#255 Changes random strings to use constants
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/M

#271 Increase creation timeout
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#272 Fix wrong condition
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#273 Add Kirk to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#265 Adding script to reset account CR
  hack/scripts/reset_account_cr.sh
Labels: approved, lgtm, size/L

#270 Standardize the different timeouts in the operator
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#276 Sets owner ref's on secrets
  pkg/controller/account/account_controller.go
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/S

#277 Revert 246 "Added credential refresh to reuse"
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/S

#280 Create accountclaim test file
  pkg/controller/accountclaim/accountclaim_controller_test.go
Labels: approved, lgtm, size/L

#274 Removes IAM specific functions to the iam.go file
  pkg/controller/account/account_controller.go
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/XL

#281 Reintroduce credential refresh to account reuse
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/XS

#282 Fix bug where missing role causes finalizer inifinite loop
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/M

#285 Update Federated Role CRs to include roleDisplayName
  deploy/crds/aws_v1alpha1_awsfederatedrole_customeradmin_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
Labels: approved, lgtm, size/XS

#287 Fix network mgmt cr and add proper descriptions
  deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
  deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
Labels: approved, lgtm, size/S

#291 Fix typo in error message
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/XS
