Repository openshift/aws-account-operator, pull requests merged in 2020-01, with the labels that each got.

#243 Add roleDisplayName for OCM user interface
  deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml
  pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/S

#231 Explicity use namespace of role ref in awsfederatedaccesscontrol
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/M

#242 Update AWS support message
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#247 Allow OCM access to federated user resources
  deploy/uhc_cluster_role.yaml
Labels: approved, lgtm, size/XS

#238 Only build BYOC aws client if needed
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/M

#250 Return when account can't be found by secretwatcher to prevent segfault
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/XS

#246 Added credential refresh to reuse
  .gitignore
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm, size/S

#249 Rotate credentials by accounts that are in Ready state
  .gitignore
  cmd/manager/main.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/credentials_rotator.go
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/L

#248 Deletes BYOCAdminAccess role and recreate if it exists
  pkg/awsclient/client.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/account_controller_test.go
  pkg/controller/account/byoc.go
Labels: approved, lgtm, size/L

#253 Added missing return
  pkg/controller/account/credentials_rotator.go
Labels: approved, lgtm, size/XS

#257 Revert "Rotate credentials by accounts that are in Ready state"
  .gitignore
  cmd/manager/main.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/credentials_rotator.go
  pkg/credentialwatcher/secretwatcher.go
Labels: approved, lgtm, size/L

#260 Wait for secret to be ready for AWSClient
  pkg/controller/account/account_controller.go
Labels: approved, do-not-merge/hold, lgtm, size/S

#261 Handle create IAM user call not succeeding but not return correctly
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/S

#262 BYOC does not supporting multiple clusters
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/utils/conditions.go
Labels: approved, lgtm, size/M

#223 Refactor BuildIAMUser and related functions
  pkg/controller/account/account_controller.go
  pkg/controller/account/iam.go
Labels: approved, lgtm, size/L

#244 Removes support cases functions to own file
  pkg/controller/account/account_controller.go
  pkg/controller/account/cases.go
Labels: approved, lgtm, size/L

#264 Add fahlmant as approver
  OWNERS
Labels: approved, lgtm, size/XS

#258 Adds consoleURL to AwsFederatedAccountAccess status
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Labels: approved, lgtm, size/M

#266 Update account_controller.go
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#267 Revert "Update account_controller.go"
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#268 Only set PendingVerification if the account is new
  pkg/controller/account/account_controller.go
Labels: approved, lgtm, size/XS

#269 Makes the consoleURL field in AWSFederatedAccountAccessStatus optional
  deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS
