Repository openshift/aws-account-operator, pull requests merged in 2020-05, with the labels that each got.

#356 Fixes keys that were changed during refactoring.
  pkg/controller/account/iam.go
Labels: approved, lgtm

#357 CreateIAMUser panic resolution
  pkg/controller/account/iam.go
Labels: approved, lgtm

#354 add resource limits/requests for the operator per OSD-2109
  deploy/operator.yaml
Labels: approved, lgtm

#343 Multipe ccs cluster support
  Makefile
  hack/scripts/aws/rotate_iam_access_keys.sh
  hack/scripts/test_envs
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/awsclient/client.go
  pkg/awsclient/iam.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/generate.go
  pkg/controller/account/iam.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountclaim/reuse.go
  pkg/controller/accountpool/accountpool_controller.go
  pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm

#359 Add generate target to generate code, mocks etc
  standard.mk
Labels: approved, lgtm

#361 Remove osdCcsAdmin AWS key rotation
  pkg/controller/account/account_controller.go
Labels: approved, lgtm

#360 Use shared types key name vars
  pkg/controller/accountclaim/reuse.go
Labels: approved, lgtm

#362 Fix Typo for memory limit
  deploy/operator.yaml
Labels: approved, lgtm

#339 Tag EC2 instances
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm

#364 fix ec2 tag resource type name
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm

#279 Put aws accounts in organization ou
  Makefile
  hack/templates/aws_v1alpha1_configmap.tmpl
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/accountclaim/accountclaim_controller.go
  pkg/controller/accountclaim/organizational_units.go
  pkg/controller/accountclaim/organizational_units_test.go
Labels: approved, lgtm, size/L

#370 Ensures godoc compatibility with iam.go
  pkg/controller/account/iam.go
Labels: approved, lgtm

#292 Cleanup secrets and access keys on reuse
  pkg/controller/account/iam.go
  pkg/controller/accountclaim/reuse.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#369 Adds secret owner refs during refresh.
  pkg/controller/account/credentials_rotator.go
Labels: approved, lgtm
