Repository openshift/aws-account-operator, pull requests merged in 2021-05, with the labels that each got.

#567 Adds necessary field for Support ARN
  deploy/crds/aws.managed.openshift.io_accountclaims_crd.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm

#570 Avoids nil pointer dereference
  pkg/controller/account/byoc.go
  pkg/controller/utils/status.go
Labels: approved, lgtm

#573 Boilerplate: Update to 0ba6566d544d0df9993a92b2286c131eb61f3e88
  .ci-operator.yaml
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/common.sh
  boilerplate/_lib/container-make
  boilerplate/_lib/subscriber
  boilerplate/_lib/subscriber-propose
  boilerplate/_lib/subscriber-propose-update
  boilerplate/_lib/subscriber-report
  boilerplate/_lib/subscriber-report-onboarding
  boilerplate/_lib/subscriber-report-pr
  boilerplate/_lib/subscriber-report-release
  boilerplate/openshift/golang-osd-operator/app-sre-build-deploy.sh
  boilerplate/openshift/golang-osd-operator/app-sre.md
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
  boilerplate/openshift/golang-osd-operator/codecov-secret-mapping
  boilerplate/openshift/golang-osd-operator/codecov.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-build.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-publish.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/common-generate-operator-bundle.py
  boilerplate/openshift/golang-osd-operator/csv-generate/common.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/operator-sdk-generate.sh
  boilerplate/openshift/golang-osd-operator/prow-config
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/golang-osd-operator/update
  boilerplate/update
  build/Dockerfile
Labels: approved, lgtm

#544 OSD-6975: Only evaluate AWS_IAM_ARN when needed
  Makefile
Labels: approved, lgtm

#540 Adds Managed Tags to AAO Created Resources
  hack/olm-registry/olm-artifacts-template.yaml
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/awsclient/iam.go
  pkg/awsclient/tags.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/byoc.go
  pkg/controller/account/ec2.go
  pkg/controller/account/iam.go
Labels: approved

#576 Improve STS related docs
  Makefile
  README.md
  docs/1.0-Installation.md
  hack/scripts/set_operator_configmap.sh
  hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Labels: approved, lgtm

#574 Fix path for CRD files
  Makefile
Labels: approved, lgtm

#579 accountclaims: Accept ExternalID when calling AssumeRole
  deploy/crds/aws.managed.openshift.io_accountclaims_crd.yaml
  pkg/apis/aws/v1alpha1/accountclaim_types.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/byoc.go
  pkg/controller/account/iam.go
Labels: approved, lgtm

#580 Make API a separate pkg
  Makefile
  go.mod
  hack/scripts/generate_crds.sh
  pkg/apis/aws/v1alpha1/account_types.go
  pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
  pkg/apis/aws/v1alpha1/register.go
  pkg/apis/aws/v1alpha1/zz_generated.openapi.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/scheme/scheme.go
Labels: approved, lgtm

#581 Removes clcollins from reviewers
  OWNERS
Labels: approved, lgtm

#559 Instead of outputting cVPU quota error just log the defaulting value
  pkg/controller/account/ec2.go
Labels: approved, lgtm, tide/merge-method-squash

#561 Initialize only the Regions available in the cluster account
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
  pkg/apis/aws/v1alpha1/shared_types.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/zz_generated.mock_client.go
  pkg/controller/account/account_controller.go
  pkg/controller/account/ec2.go
Labels: approved, lgtm, tide/merge-method-squash

#591 Update OWNERS file
  OWNERS
Labels: approved, lgtm

#583 Boilerplate: Update to 5fea264b458ec33913afb04eda6ff87d8013d9f4
  .ci-operator.yaml
  .gitattributes
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/common.sh
  boilerplate/_lib/freeze-check
  boilerplate/_lib/release.sh
  boilerplate/_lib/subscriber-propose-update
  boilerplate/_lib/subscriber-report-release
  boilerplate/_lib/subscriber.sh
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-build.sh
  boilerplate/update
  build/Dockerfile
Labels: approved, lgtm
