Repository openshift/aws-account-operator, pull requests merged in 2023-04, with the labels that each got.

#754 Update ubi-micro image via boilerplate-update
  boilerplate/_data/last-boilerplate-commit
  build/Dockerfile.olm-registry
Labels: lgtm, approved

#755 OSD-14723: Adding AMI for enabling ap-southeast-4
  fips.go
  hack/olm-registry/olm-artifacts-template.yaml
Labels: lgtm, approved, jira/valid-reference

#751 When an AWSFederatedRole CR is updated, automatically update all associated AWSFederatedAccountAccess CRs
  api/v1alpha1/shared_types.go
  controllers/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  controllers/awsfederatedaccountaccess/awsfederatedaccountaccess_controller_test.go
  controllers/awsfederatedrole/awsfederatedrole_controller.go
  controllers/awsfederatedrole/awsfederatedrole_controller_test.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/zz_generated.mock_client.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved

#757 Make sure to add federated role label to existing accounts if not present
  controllers/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved, tide/merge-method-squash

#758 Adds make targets back and fixes them for local dev
  Makefile
  test/integration/int-testing.mk
  test/local/create_account.sh
  test/local/create_federated_role.sh
  test/local/delete_account.sh
  test/local/delete_account_secrets.sh
Labels: lgtm, approved

#759 Enable new region me-central-1 for cloud provider operators
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Labels: lgtm, approved, tide/merge-method-squash

#760 Update docs outlining the responsibilities of federated role and accountaccess controllers
  docs/3.4-AWSFederatedRole.md
  docs/3.5-AWSFederatedAccountAccess.md
Labels: lgtm, approved
